---
- name: Check variables consistency
  assert:
    that: |
      (
        (
          theo_agent_verify_signature|bool and
          theo_agent_public_key|string|length|int > 0 and
          theo_agent_public_key|string != 'None'
        ) or
        not theo_agent_verify_signature|bool
      )

- name: Check current theo-agent version
  command: theo-agent --version | grep '^Version:' | awk '{ print $2 }'
  register: theo_agent_current_version
  changed_when: false
  failed_when: false

- name: Set public key path for config
  set_fact:
    theo_agent_config_public_key_path: "public_key: {{ theo_agent_public_key_path }}"
  when: theo_agent_verify_signature|bool

- name: Set public key path for config
  set_fact:
    theo_agent_config_public_key_path: ""
  when: not theo_agent_verify_signature|bool

- name: Delete existing theo-agent version if different
  file:
    path: "{{ theo_agent_path }}"
    state: absent
  when: >
    theo_agent_current_version.stdout is defined
    and theo_agent_version not in theo_agent_current_version.stdout

- name: Install theo-agent executable
  get_url:
    url: https://github.com/theoapp/theo-agent/releases/download/v{{ theo_agent_version }}/theo-agent-{{ ansible_system }}-{{ ansible_architecture }}
    dest: "{{ theo_agent_path }}"
    mode: 0755

- name: Add theo-agent user
  user:
    name: "{{ theo_agent_user }}"
    comment: "Theo Agent"
    shell: /bin/false
    system: yes

- name: Create cache directory
  file:
    path: "{{ theo_agent_cache_dir }}"
    state: directory
    owner: "{{ theo_agent_user }}"
    mode: 0755

- name: Create config directory
  file:
    path: "{{ theo_agent_config_dir }}"
    state: directory
    mode: 0755

- name: Create config file
  template:
    src: config.yml.j2
    dest: "{{ theo_agent_config_path }}"
    mode: 0644

- name: Create public key file
  copy:
    dest: "{{ theo_agent_public_key_path }}"
    mode: 0644
    content: "{{ theo_agent_public_key }}"
  when: theo_agent_verify_signature|bool
