---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy
# See: https://github.com/ansible/galaxy/issues/46

name: release

on:
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: ansible-theo-agent

jobs:
  release:
    name: Release to Galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: ansible-theo-agent
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip3 install ansible-base
      - name: Import to Galaxy
        run: ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} | cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
